sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t abhinavroy23/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abhinavroy23/docker-react yarn test --coverage

